#!/bin/bash
ELK_SYSTEM_CONF="/udata/.elk-system/elk-system.conf"
if [ -e $ELK_SYSTEM_CONF ]; then
    source $ELK_SYSTEM_CONF
else
    echo "No elk-system.conf file found ! Using default config."
    mkdir -p /udata/.elk-system
    cp /etc/elk-system.conf /udata/.elk-system/
    source /etc/elk-system.conf
fi

modprobe audio_rtdm audio_buffer_size=$AUDIO_BUFFER_SIZE audio_hat=$AUDIO_HAT

if [ $AUDIO_HAT = "elk-pi" ]; then
    modprobe shiftreg_rtdm adc_chans_per_tick=4
fi

modprobe i2c_dev
rfkill unblock all

# Set CPU Speed
echo userspace > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
SYS_CPUFREQ=/sys/devices/system/cpu/cpu0/cpufreq/scaling_${CPU_SPEED}_freq
cat $SYS_CPUFREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
sync

DEVICE="/dev/rtdm/audio_rtdm"

if [ -e $DEVICE ]
then
    echo "audio_rtdm loaded"
    fsck -y /dev/mmcblk0p1
    mount /dev/mmcblk0p1 /boot
    fw_setenv boot_count 0
    sync
    umount /boot
    fsck -y /dev/mmcblk0p1
    exit 0
else
    echo "audio_rtdm failed"
    exit 1
fi
