#!/bin/bash

# Mount udata partition
mount /dev/mmcblk0p4 /udata

if [ -f /udata/change_perms ]; then
    chown -R mind:mind /udata
    chown -R root:root /udata/.elk-system
    rm -f /udata/change_perms
    sync
fi

ELK_SYSTEM_CONF="/udata/.elk-system/elk-system.conf"
if [ -e $ELK_SYSTEM_CONF ]; then
    source $ELK_SYSTEM_CONF
else
    echo "No elk-system.conf file found ! Using default config."
    mkdir -p /udata/.elk-system
    cp /etc/elk-system.conf /udata/.elk-system/
    source /etc/elk-system.conf
fi

# Probe audio codecs and detect the audio hat
i2cdetect -y 1 0x4c 0x4f | grep "^40:" | sed 's/^40://' | grep "4[cdef]" > /dev/null
if [ $? -eq 0 ]; then
    I2C_PCM5122_DETECTED=true
else
    I2C_PCM5122_DETECTED=false
fi
i2cdetect -y 1 0x4a 0x4a | grep "^40:" | sed 's/^40://' | grep "4a" > /dev/null
if [ $? -eq 0 ]; then
    I2C_PCM1863_DETECTED=true
else
    I2C_PCM1863_DETECTED=false
fi
i2cdetect -y 1 0x44 0x44 | grep "^40:" | sed 's/^40://' | grep "44" > /dev/null
if [ $? -eq 0 ]; then
    I2C_PCM3168A_DETECTED=true
else
    I2C_PCM3168A_DETECTED=false
fi
i2cdetect -y 1 0x60 0x60 | grep "^60:" | sed 's/^60://' | grep "60" > /dev/null
if [ $? -eq 0 ]; then
    I2C_CLKGEN_DETECTED=true
else
    I2C_CLKGEN_DETECTED=false
fi

if $I2C_PCM5122_DETECTED; then
    if $I2C_PCM1863_DETECTED; then
        AUDIO_HAT="hifi-berry-pro"
    else
        AUDIO_HAT="hifi-berry"
    fi
elif $I2C_PCM3168A_DETECTED || $I2C_CLKGEN_DETECTED; then
    AUDIO_HAT="elk-pi"
else
    AUDIO_HAT="elkpi-stereo"
fi
echo "HAT is $AUDIO_HAT"
echo $AUDIO_HAT > /tmp/audio_hat

# Detect isolcpu settings
ISOLCPU=`cat /sys/devices/system/cpu/isolated | cut -d'-' -f 1`
if [ -z "$ISOLCPU" ]; then
    echo "No isolcpu"
    ISOLCPU=0
else
    echo "isolcpu = ${ISOLCPU}"
fi

# Probe the audio driver
if [ $AUDIO_HAT = "hifi-berry-pro" ] || [ $AUDIO_HAT = "hifi-berry" ]; then
    modprobe rpi-audio-evl audio_buffer_size=$AUDIO_BUFFER_SIZE audio_hat=$AUDIO_HAT audio_irq_affinity=$ISOLCPU
    # Give perms for userspace to access audio driver class
    chown -R mind:mind /sys/class/audio_evl
else
    echo "Sorry, no audio driver for HAT $AUDIO_HAT in this version."
    touch /tmp/hat-not-supported
fi

# Ensure wireless devices are not blocked
rfkill unblock all

# Set CPU Speed
echo userspace > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
SYS_CPUFREQ=/sys/devices/system/cpu/cpu0/cpufreq/scaling_${CPU_SPEED}_freq
cat $SYS_CPUFREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
sync

if [ -e /dev/audio_evl ]
then
    echo "audio driver loaded"
    exit 0
else
    echo "audio driver load failed"
    touch /tmp/audio-driver-load-failed
    exit 1
fi
