require conf/distro/poky.conf

DISTRO = "elk"
DISTRO_NAME = "ELK Poky based distribution for Yocto Project"
DISTRO_VERSION = "${ELK_AUDIO_OS_VERSION}"

MAINTAINER = "ELK"
TARGET_VENDOR = "-elk"
LOCALCONF_VERSION = "1"

DISTRO_FEATURES:append = " systemd bluetooth wifi"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"

# systemd does not fully support /home/root
ROOT_HOME ?= "/root"

# This platforms supports an EVL co kernel
DISTRO_FEATURES:append = " evl pam"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

PREFERRED_PROVIDER_virtual/kernel_raspberrypi4-64 = "linux-raspberrypi"

PREFERRED_VERSION_linux-raspberrypi = "6.6.%"

DISTRO_FEATURES:remove = "${@bb.utils.contains('INSTALL_X11_SUPPORT', '1', 'wayland', 'wayland x11', d)}"

PREFERRED_VERSION_xenomai-lib_raspberrypi4-64 = "3.2"

IMAGE_FSTYPES = "rpi-sdimg"

SECURITY_STACK_PROTECTOR = ""

# Remove this overlay from list of overlays as kernel does not have this
# but meta-raspberrypi rpi4 machine conf requires it.
RPI_KERNEL_DEVICETREE_OVERLAYS:remove = "overlays/vc4-fkms-v3d-pi4.dtbo"

# Remove overlay from boot files
IMAGE_BOOT_FILES:remove = "vc4-fkms-v3d-pi4.dtbo;overlays/vc4-fkms-v3d-pi4.dtbo"

# brcmfmac modules
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "kernel-module-brcmfmac kernel-module-brcmfmac-wcc"
